package processor

var dbTables = []string{
	"account_erc20_transfers",
	"barn_delegate_actions",
	"barn_delegate_changes",
	"barn_locks",
	"barn_staking_actions",
	"bond_transfers",
	"compound_controller_harvests",
	"compound_provider_transfer_fees",
	"erc721_transfers",
	"governance_abrogation_proposals",
	"governance_abrogation_votes",
	"governance_abrogation_votes_canceled",
	"governance_events",
	"governance_proposals",
	"governance_votes",
	"governance_votes_canceled",
	"jtoken_transfers",
	"smart_yield_junior_buy",
	"smart_yield_junior_redeem",
	"smart_yield_prices",
	"smart_yield_rewards_claims",
	"smart_yield_rewards_staking_actions",
	"smart_yield_senior_buy",
	"smart_yield_senior_redeem",
	"smart_yield_state",
	"smart_yield_token_buy",
	"smart_yield_token_sell",
	"smart_yield_transaction_history",
	"yield_farming_actions",
	"treasury_transfers",
	"labels",
}
