package auction

const AuctionCreated = "LogAuctionCreated"
const ERC721Deposit = "LogERC721Deposit"
const ERC721Withdrawal = "LogERC721Withdrawal"
const BidSubmitted = "LogBidSubmitted"
const BidWithdrawal = "LogBidWithdrawal"
const BidMatched = "LogBidMatched"
const AuctionExtended = "LogAuctionExtended"
const AuctionCanceled = "LogAuctionCanceled"
const AuctionRevenueWithdrawal = "LogAuctionRevenueWithdrawal"
const ERC721RewardsClaim = "LogERC721RewardsClaim"
const RoyaltiesWithdrawal = "LogRoyaltiesWithdrawal"
const SlotRevenueCaptured = "LogSlotRevenueCaptured"
const AuctionFinalized = "LogAuctionFinalized"
